### PR TITLE
update meta data

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by palmskog** [comment]
@CohenCyril can I push an update to this with some Coq-community adjustments? Or do you want to do it?

**Comment by CohenCyril** [comment]
Hi @palmskog sorry for the delay. Sure please amend accordingly when you have the availability.

**Comment by palmskog** [comment]
@CohenCyril I did the boilerplate update, this is ready to merge

**Comment by CohenCyril** [comment]
@palmskog I wish we kept the nix instruction for custom build before the coq-elpi patch is integrated... Is there a reason not to?

**Comment by palmskog** [comment]
@CohenCyril ah, they disappeared because they were not in `meta.yml`. Sorry, I will re-add them.

**Comment by palmskog** [comment]
Now I think we are good and `meta.yml` is used to generate `README.md`.

**Comment by palmskog** [comment]
@CohenCyril unless you have concerns, I will merge this later today, since I think it provides some important information for anyone visiting/cloning the repo. We can always amend later.

**Pull request merged**
